databases:
  - name: bitespeed-db
    plan: free
    databaseName: bitespeed
    user: bitespeed

services:
  - type: web
    name: bitespeed-identity
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
      - key: LOG_LEVEL
        value: info
